### ISSUE TITLE
Cannot disconnect & reconnect without exiting entire application

### ISSUE THREAD

**Issue by starrychloe** [OpenBazaar/openbazaar-desktop#1054]
Brief Description: Whenever you try to disconnect and reconnect, it gives an error. If you are connected without TOR, and try to disconnect and reconnect with TOR, it always gives an error. Even though exiting the entire application and start it again will successfully connect with TOR. Even if you uncheck TOR and try to connect again, it still fails. The only way to connect is to kill the app and start over.

Operating System (OS and version): Windows 8.1
OpenBazaar version (shown on `About OpenBazaar` page in menu):  client 2.0.14, server 0.9.3
Hardware: Intel, lots of RAM

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce):  Always

Steps to reproduce:
1.  Connect
2.  Disconnect
3. Turn on TOR
4.  Reconnect

Observed Behavior:
It says it can't connect.

Expected Behavior:
I expect it to connect.

Additional info (links, images, etc go here):

Log: https://gist.github.com/starrychloe/c9c322e1ef2fc6230af5c1442d831763

**Comment by rmisio** [comment]
This is because the client will not try and reconnect until the server has fully shut down. The server was recently updated to not shut-down until a bunch of cleanup is done. It looks like that cleanup is taking longer than the 30 seconds the client allows for the connection attempt. So... I think it's just timing out.

When you completely shut-down and restart the app, the app has no knowledge of a previous server in the process of being shut-down, so it just bypasses that check.

Ideally, you don't want to start a server if a previous one is not completely shut-down because it may have a hold of the DB and / or some ports that the new server instance would need. I'll have to think if there's anything we could do about this.
