### ISSUE TITLE
Hide Shipping Info Until Payment is Confirmed

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1095]
Sellers sometimes ship orders before a payment is made, which leads to confusion and lost money. The shipping information for the buyer should not be displayed in the order details until after the order has been paid and the transaction has at least 1 confirmation.

**Comment by rmisio** [comment]
> The shipping information for the buyer should not be displayed in the order details until after the order has been paid and the transaction has at least 1 confirmation.

Do we really want to hide it until it has 1 confirmation or until the payment is seen? If I'm not mistaken, the order state updates as soon as the payment is seen. Also, in the UI we add the `Paid in Full` text at that point as well. So... it would be a bit inconsistent to base the visibility of the shipping address on 1 confirmation. Is that inconstancy bad UX? 

Something else to keep in mind. We are currently not updating that confirmation count in real-time because of this server bug:
https://github.com/OpenBazaar/openbazaar-go/issues/647

If we follow through with the 1 confirmation approach, we'd probably want to fix that bug, otherwise if the vendor happens to be viewing the order while that confirmation comes in, they'll need to manually refresh. Since almost everything else updates in real time, it would probably be better (less confusing) not to start introducing things that require a manual refresh.

**Comment by morebrownies** [comment]
I opened up #736 a while back too.

In general, I agree that doing anything we can to prevent the vendor from shipping an item before it has been paid for is a good idea.

**Comment by TheButterZone** [comment]
As a seller I'd like to know the shipping info in advance of payment being broadcast so I can charge the buyer exact shipping instead of over/undercharging.

**Comment by jjeffryes** [comment]
I'm closing this as not needed.
