### ISSUE TITLE
OB News

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1132]
We need an easy way to provide important information to all users, especially in light of recent abuses of the network by people running scams. 

A simple MVP to do this would be to show a News modal with news pulled from an external source.

The news endpoint would be called on startup and once an hour, and would show the news modal if the publication date was different from the last time the news was shown (or id, or some other unique identifier). 

A news icon would be added to the top bar, so users that have dismissed the news can open it again if they want to reread it.

Most news content would be cumulative, with new bulletins added above old ones, and old bulletins being removed from the news content when they are no longer relevant.

Some quick mockups are shown below:

![image](https://user-images.githubusercontent.com/1584275/33614790-4cc07d5c-d9a6-11e7-9e4f-8d19948f1391.png)

![image](https://user-images.githubusercontent.com/1584275/33614684-16110128-d9a6-11e7-9f59-ae83b393d374.png)

**Comment by hoffmabc** [comment]
I think the news would need to be signed with out pgp key to verify it’s from us. This would need to be trustworthy.

**Comment by rmisio** [comment]
> The news endpoint would be called on startup and once an hour, and would show the news modal if the publication date was different from the last time the news was shown (or id, or some other unique identifier).

If there's new news on startup, I suppose we could show the modal, but I don't think I'd just pop it up on new news after startup. The user may be in the middle of something and I would think it would be super annoying to just have this pop up at some random time. We'd probably want some indicator of some sort that there is new news that the user would have to click.

Similar situation if new news comes in while they have the modal open. I don't think you just want to push it to the top since the user may be reading the news and that would cause an annoying page jump. Probably want some type of "refresh" pop in message.

**Comment by rmisio** [comment]
Is there a reason we have a "close" button at the bottom of the modal, instead of using the standard modal close (top right)?

**Comment by rmisio** [comment]
Another factor is that eventually we're going to want to paginate this endpoint. If it keeps growing endlessly with news it will eventually cause latency and rendering problems. I suppose though we could defer that, since it would probably be a while before the content got large enough for that scenario.

**Comment by jjeffryes** [comment]
We could have an indicator that there is new news once an hour instead. Good point about it interrupting actions if it pops up.

There's no particular reason for the close button instead of the top right close icon.

We don't need pagination. As mentioned in the write up, we'd remove old news, with the goal of it always being small enough to be read easily.

**Comment by rmisio** [comment]
Since we decided to punt on this one for now, I'll close the issue. We could always re-open if we switch course.
