### ISSUE TITLE
Prevent Too Long Values in Shipping

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#115]
It's possible to enter too long/large values in the shipping section, the inputs should have max attributes to prevent the user from entering an invalid value and not knowing until the error message is shown.

![image](https://cloud.githubusercontent.com/assets/1584275/20808978/9e008712-b7d2-11e6-886c-d93ce2cb7b20.png)

![image](https://cloud.githubusercontent.com/assets/1584275/20808958/8f65a994-b7d2-11e6-953f-64f6f74f7688.png)

![image](https://cloud.githubusercontent.com/assets/1584275/20809001/adae73ea-b7d2-11e6-843b-58e5bb826f48.png)

**Comment by rmisio** [comment]
Closing this as too broad of an issue.

There are still some gaps in the validation of the listing between what the server validates and what the client validates, but the gaps are quite extreme cases and they are something I plan to address with any random odd hours I find at the end of days / weeks.

Re: validating large numbers - as was discussed, the html max attribute doesn't work as we;d like for numeric input. It would take some time to have to retrofit all models to have this validation and I question it's need, since the max number allowed is  9,223,372,036,854,775,807. It's almost certain that a user will not accidentally enter such a number. If they do, the back end will fail validation and an error message will be displayed. That seems like enough to handle such an extreme case.
