### ISSUE TITLE
Was infected with a virus after updating to latest version

### ISSUE THREAD

**Issue by charlierlee** [OpenBazaar/openbazaar-desktop#1292]
Brief Description: 
After updating openbazaar using the prompt to update (not downloading from main website), I was told by Windows Defender that I received a virus. Specifically: trojan:win32 azden.a!cl
I was connected over TOR because that is super cool up until this point. I'm thinking it was a man in the middle attack. I'm not sure how this could have happened.

Operating System (OS and version): 
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: Lenovo w530

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Could not reproduce

Steps to reproduce:
1. Open Openbazaar
2. get prompted to download latest version
3. download latest version of openbazaar through app (not through browser)
4. Installation runs
5. Windows Defender detects Win32/Azden.A!cl

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
We've seen that reported by a few people, as far as we can tell it's a false positive from Windows Defender. We haven't seen any sign of a virus in our code, and the download should be secure. 

This specific warning seems to happen to other projects that use Electron, we've contacted Microsoft to try and resolve it.

**Comment by charlierlee** [comment]
I have a copy of the file, and it is a different binary than what I got after installing from website.

**Comment by hoffmabc** [comment]
Can you please post the hashes and file names of the two binaries you’re comparing? The web site redirects to GitHub directly so it’s highly unlikely these two files are different in any way.

**Comment by charlierlee** [comment]
I only made a backup of the file (openbazaard.exe) that Windows Defender detected as a virus. Here is the hash:
C:\Users\charl\AppData\Local\OpenBazaar2\app-2.1.1\resources\openbazaar-go\openbazaard.exe

1a786378c4dae86bbfbf68d83897127bc1d8eba28f9bd2cdea5f9cb4bf124041  openbazaard.exe sha256

49113e8a1cbc06483abec0ed76671297b0d9d67c  openbazaard.exe sha1

**Comment by hoffmabc** [comment]
Visiting that link @charlierlee you see that every single checker except Microsoft is clean for that file. I believe it's a false positive for some reason. 

The reason the hashes don't match is that our build was made using the RC2 of the server located here: https://github.com/OpenBazaar/openbazaar-go/releases/download/v0.11.1-rc2/openbazaar-go-windows-4.0-386.exe whose hash DOES match the one above. There is no code difference between our v0.11.1 and v0.11.1-rc2 releases but the hashes are different due to build. There is no MITM attack on these files.

HASH: 1a786378c4dae86bbfbf68d83897127bc1d8eba28f9bd2cdea5f9cb4bf124041
https://github.com/OpenBazaar/openbazaar-go/releases/download/v0.11.1-rc2/openbazaar-go-windows-4.0-386.exe

You can double check. I'm going to close this issue as a false positive and cleared up about the hashes mismatching.
