### ISSUE TITLE
module.js:438 Uncaught Error: Cannot find module 'underscore'

### ISSUE THREAD

**Issue by mariodian** [OpenBazaar/openbazaar-desktop#13]
I'm getting the above error in the chrome console on the lastest git pull. Electrum window looks like this:

![screen shot 2016-07-17 at 12 16 24 am](https://cloud.githubusercontent.com/assets/3636406/16895841/b9964a38-4bb3-11e6-8c70-e32538cdeb1d.png)

**Comment by AubreyF** [comment]
Hi, Mariodian! I ran into this issue as well - and was able to resolve it by deleting my local node_modules directory and rerunning npm install. 

Since npm doesn't revalidate recursive dependency chains during subsequent install processes, a failed/partial initial install can result in a node_modules state which npm doesn't know how to recover from.

https://github.com/npm/npm/issues/1341

**Comment by rmisio** [comment]
Either way we failed to explicitly declare underscore as a dependency in our package.json and since we're directly importing it, we should be.

Anyhow, I've fixed it here (should be merged into master soon):
https://github.com/OpenBazaar/openbazaar-desktop/pull/14
