### ISSUE TITLE
The modal/overlay transparent background should inherit the theme's secondary_color 

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#132]
It currently hardcoded to dark gray. 

<img width="1280" alt="screenshot 2016-12-02 11 02 23" src="https://cloud.githubusercontent.com/assets/13066886/20846878/8baf675a-b880-11e6-9537-21b195730f1c.png">

**Comment by rmisio** [comment]
I assume it should have some transparency?

If so, there might be some complexity there, because if we just hard code a certain transparency, it will result in a very different effect depending on the lightness / darkness of the users secondary color.

We ran into a similar issue with disabling elements where using a single transparency value for all elements was problematic because the transparency just couldn't satisfy both light and dark text colors. There's a [trello card](https://trello.com/c/RPWPj5vA/207-create-theme-driven-disable-style) to have the disabled state be aware of the color it's being applied to and base the transparency value off of that.

Sounds like me might need the same treatment here.

**Comment by morebrownies** [comment]
Let me make sure I'm communicating this clearly.

Currently the modal/overlay background is hardcoded to a darkish gray color. The modal itself is using the primaryColor. 
<img width="1280" alt="screenshot 2016-12-02 11 02 23" src="https://cloud.githubusercontent.com/assets/13066886/20852843/ff7929de-b89c-11e6-837b-42bab0125b23.png">

Instead of hardcoding a background color, we'll want to be theme friendly and use the secondaryColor here. I'm pretty sure this should play nicely across light and dark themes, but we'll definitely want to test it more. 
![screenshot 2016-12-02 14 38 07](https://cloud.githubusercontent.com/assets/13066886/20852841/f9509682-b89c-11e6-8027-4089e64f0706.png)

I set the opacity to 90% in all of the Sketch designs.

**Comment by rmisio** [comment]
yeah, ok, I guess it will probably work. Sorry, I guess I could of tested it. I know that with the disabled state, there was a very big difference when a singular transparency were applied to light vs. dark text. One setting made the light text nearly disappear, whereas an opposite setting made the dark text not look disabled at all.

Seems like that's not happening here.

**Comment by morebrownies** [comment]
No worries, I think this is actually a very simple change. I'll submit a PR for it later and we can test.

**Comment by rmisio** [comment]
unless someone goes really crazy and sets a really really dark secondary color, but I guess we could chalk that up to poor user judgement:

![image](https://cloud.githubusercontent.com/assets/794517/20853221/79f45b78-b89f-11e6-8fa4-19b5b663f7eb.png)

**Comment by morebrownies** [comment]
The secondaryColor is actually intended to be the same as the body background color, so the colors should flow consistently through the primary layer and modal layer.

I believe there are 5 colors that can be set:
primary_color (used in listing cards, navigation, modals, etc)
secondary_color (used as the body background and overlay background)
text_color
highlight_color (used for notification badges and things to highlight)
hightlight_color_text
