### ISSUE TITLE
Make transaction ID in order details clickable if it's a link

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1338]
Sellers may paste a link to a transaction ID in a crypto listing when fulfilling the order instead of just the tx, it would be nice to make it clickable if it is.

**Comment by morebrownies** [comment]
Something to consider...I think it could be dangerous to encourage people to paste links into the transaction ID input. It's possible users may exploit this and link to block explorers that are non legitimate and carry out fraud attacks that way. Encouraging users to include ONLY the transaction ID may be the safest approach. Might be worth floating this question around to some of the other devs too to see if I'm being overly conservative here.

**Comment by jashot7** [comment]
I'll also add here (from earlier discussion with @morebrownies) that if we decide to accept my fix/enhancement, we update the UI to point out to the users that they may enter either an ID or a URL:

```TLDR: I think this needs to be changed to something like:

Label: *Transaction ID / Link* Placeholder: *Paste the Transaction ID or Link*

This would require a change in our translations, so I’m not sure how that would work.```

**Comment by rmisio** [comment]
> Something to consider...I think it could be dangerous to encourage people to paste links into the transaction ID input.

I totally agree with that. This bug felt a little sketchy to me from the start.

**Comment by morebrownies** [comment]
Maybe the bug should more so be: _Prevent users from entering links into the transaction ID input_

**Comment by rmisio** [comment]
> Maybe the bug should more so be: Prevent users from entering links into the transaction ID input

That totally makes sense, but that really wouldn't work here because we're trying to support thousands of coins with potentially thousands of different tx id formats. It sounds far-fetched, but can we guarantee `HTMLCoin`s tx id format wouldn't be `<a>abcdefg</a>`.

I think to be non prohibitive and future-proof we just need to be quite liberal on what we allow in the field and then truncate the field in the UI as necessary and flatten any html.. just so it doesn't break any layouts. Anyhow, I'll write an issue for that suggestion.

**Comment by rmisio** [comment]
Closing this since making a link could be aiding vendors posting nefarious links.
