### ISSUE TITLE
Followers do not update in header on 'My Page'

### ISSUE THREAD

**Issue by BillStrait** [OpenBazaar/openbazaar-desktop#1417]
Brief Description: 
When a new follower arrives while the client is running, the follower count on 'My Page' does not update. clicking over to the 'Followers' tab will display the correct number. Refreshing does not update the followers count. Restarting the client will update the followers count.

Operating System (OS and version): Windows 10 build 17134

OpenBazaar version (shown on `About OpenBazaar` page in menu): Client 2.2.1, server 0.12.0
Hardware: a desktop pc.

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Start OB Client and take note of your follower count.
2. Get a new follower.
3. Observe the follower count did not increase.

Observed Behavior: Follower count stays the same.

Expected Behavior: Follower count should increment with the number of followers.

**Comment by rmisio** [comment]
This is working as intended. The initial counts are coming from the profile and they are cached. Once you click on the actual tab, we make a different call which gets more accurate counts. But, we don't want to just make that extra call blindly because in most cases the user will not even be interested in the follow / follower counts and them being off will be of no consequence.
