### ISSUE TITLE
Multicoin Integration - Onboarding [ROUGH DRAFT]

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1424]
## User Story
As a user, when I am going through onboarding, I want to be able to choose the multicoin wallet or an SPV wallet, and have the differences between it and the SPV wallets clearly explained.

## Functional Requirements
- [ ] One of the options should be the multicoin wallet, with details explaining that it accepts [show list of current coins] and that it connects with an outside API. The ramifications for the user’s security should also be explained.
- [ ] We might want to group the SPV wallets together visually to show they’re similar vs. the multicoin wallet.

**Comment by rmisio** [comment]
> As a user, when I am going through onboarding, I want to be able to choose the multicoin wallet or an SPV wallet, and have the differences between it and the SPV wallets clearly explained.

Hmm... well I think there were some differing philosophies on this ranging from SPV being the default wallet to SPV just being an advanced configuration option.

I recall there being a lot of support for the latter since offering the ability in the interface to toggle between an SPV wallet and a multi-coin one likely involves a good amount of scope (and rabbit holes and likely the ability to botch in progress orders). The scope is probably significantly disproportionate to the number of users who would actually care to use an SPV wallet (at least intentionally).

**Comment by jjeffryes** [comment]
This issue was made obsolete by our kickoff discussion.
