### ISSUE TITLE
Add an Optional Refund Address to Purchases [Rough Draft]

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1433]
## User Story
As a user, if I use an external wallet, I would like any funds from refunds, cancellations, or disputes to go to that wallet instead of the app's internal wallet.

## Functional Requirements
- [ ] In the purchase screen, there should be an input for a refund address. This input is optional.
    - We may want to hide the input behind a "add external refund address" button or otherwise de-emphasize it.
- [ ] The refund address should be added to the purchase data.
- QUESTION: Should the address be validated?
- QUESTION: Where in the order details should be address be shown? Is showing it sufficient, or does it need other functionality?
- QUESTION: How does the refund address affect the order flow? Does tracking the order state work the same?

## Server Changes
- The purchase API should accept a refundAddress field, and use that address when sending funds to the buyer from the purchase.
- The refundAddress field should be validated, and a clear error returned with an error code for internatinalization if it is invalid.

NOTE: the refund address is needed for the web based buying client, this will serve as a POC for that element of it.

**Comment by rmisio** [comment]
> QUESTION: Should the address be validated?

I would think so since we validate the address providing in the wallet send api. What we do there is have it driven by the config file on the client, so if the config file provides a validation function, we validate it client side before even deciding to send it to the server. The server should always have validation.

I believe we validate BTC client side, but not the others, since I was told there aren't good JS libs for validating ZEC and BCH addresses at this time (didn't put too much effort into seeking any out and having the thing fail on the server isn't the end of the world).

**Comment by jjeffryes** [comment]
As long as the server is validating the refund addresses, that's probably good enough.

**Comment by jjeffryes** [comment]
We've determined this isn't a feature we plan to support in reference client. If there is sufficient  demand, we can re-open it.
