### ISSUE TITLE
Improve Can't Purchase Message

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1546]
When you don't have the right coin type to purchase a listing, the buy button shows a "This listing is not purchasable." error message. This is confusing, and implies something might be wrong with the purchase (we've had some comments about that in support requests).

It would be good to clarify the text here to say it's because of the coin type.

Also, the warning icon is on the right for some reason instead of the left.

![image](https://user-images.githubusercontent.com/1584275/44791424-95ef2f00-ab6f-11e8-9c3b-5044a05bc722.png)

**Comment by rmisio** [comment]
There is more information in a tooltip if you hover over the icon. I imagine it's not clear that it's a tooltip, so I suppose we could move the text elsewhere - just a matter of where it makes sense design wise.

In general though, IMHO, it would be much better if it could be clearer somehow there is a tooltip there since tooltips allow us a very concise way (real estate friendly way) to add more information. Maybe we change the warning icon to an info icon? We do have this type of tooltip pattern in several other parts of the app.

**Comment by jjeffryes** [comment]
I actually didn't realize there was a tooltip at all. Apparently the people complaining in support didn't either. Switching the warning icon to the (i) icon that we mostly use for tooltip info would help I think.

**Comment by rmisio** [comment]
@jjeffryes Better?

![image](https://user-images.githubusercontent.com/794517/45108331-8fc1fb00-b0f9-11e8-9cfd-3d9a0a680088.png)

**Comment by jjeffryes** [comment]
@rmisio I think that looks nicer. Good work.

**Comment by rmisio** [comment]
This should be fixed in the `multi-wallet` branch.
