### ISSUE TITLE
Add Bulk Coin Accepted Control

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1683]
Add a control in settings/advanced to allow users to update the cryptocurrencies accepted by all their listings at once using the new bulkupdatecurrency API.

The API endpoint is POST http://localhost:4002/ob/bulkupdatecurrency

The data it expects is { "currencies":["ZEC", "BTC", "BCH", "LTC"] }

https://github.com/OpenBazaar/openbazaar-go/pull/1423

![image](https://user-images.githubusercontent.com/1584275/51627172-530f6880-1f0f-11e9-9c4f-77272834550f.png)

**Comment by jjeffryes** [comment]
@rmisio and @morebrownies I took the screenshot from a version where I quickly added the control to the template, it looks ok to me. I don't think making it functional would be much work.

Do either of you think we need a tool tip similar to the one in purchasing to confirm they really want to change all their listings?

**Comment by placer14** [comment]
FYI, this is likely going to take time for larger stores. It also potentially produces an error if it fails. If it fails, it would be unrecoverable right now since it could be dead at any point during the application. On the bright side, there's nothing wrong with trying over and over (idempotency++) but it'll likely fail once it hits that listing again. Due to using maps internally, the order processing will be different each time so hitting it again might process a few more listings (or none at all).

**Comment by jjeffryes** [comment]
If it's a high-risk operation, I'm fine with not having it in the UI, and leaving it as a thing very interested users have to do from the command line.

**Comment by placer14** [comment]
I think a failure wouldn't leave the node inoperable. It uses the same behavior that a single listing edit uses. We just wouldn't know which listings were actually updated without looking at them. I don't think that's a dealbreaker. And this is in the Advanced section of settings. Just letting you know of the behavior to expect from it when considering the UX around initiation/feedback within the UI.

**Comment by hoffmabc** [comment]
FYI: As a benchmark for 2800 listings, CryptoCollectibles took a little over 30 seconds to process.

**Comment by jjeffryes** [comment]
> I wonder if it would be better to add a Apply to All listings button to Settings > Store.

I like that idea. The only caveat is the difference between saving the whole section and clicking the apply button could be confusing.

Maybe have a checkbox for "apply these changes on save to existing listings" under the control? So when you save the section it also updates everything.

**Comment by jjeffryes** [comment]
On the other hand, having a separate button makes some things a little simpler, since it keeps the two API calls separate too. I could go either way.

**Comment by morebrownies** [comment]
I could go either way too. A checkbox that is checked by default would be best, but not absolutely mandatory if it adds a lot of overhead. 

☑️ Apply to all my listings

**Comment by rhcastilhos** [comment]
Adding a single Coupon to multiple listings in a bulk update in Settings > Store would also be a nice feature.

**Comment by jjeffryes** [comment]
One weird thing that would happen with a checkbox is you'd have to open settings, not change anything, and hit the save button to apply it.

Which then gets weird in the code, since we don't have a way to tell if the listings have already been updated or not, and we don't want to update all of them every time someone saves anything in that section.

I think a separate button is much better now that I'm thinking about it.

**Comment by rmisio** [comment]
I agree with the api coded as I suspect it is, it's very basic and potentially high-risk.

Some things to keep in mind:

- it's less than ideal for this to be an api call that doesn't return until it's done because it means the limited http request queue will have one less spot open for a while.

- if the user happens to refresh the app during it's operation, when they come back the state of an in-progress update will be lost.

----> At the very least I'd follow the pattern we use for some of the other operations where we put the call into a seperate module decoupled from the settings view. That way if they leave settings and come back, the state isn't lost. You'd probably want something like this:

`function bulkCoinUpdate() {}`

`function isBulkCoinUpdating() {}`

have the module fire the following events: `bulkCoinUpdating`, `bulkCoinUpdateDone`, `bulkCoinUpdateFail`.

**Comment by hoffmabc** [comment]
It's actually probably better that users don't go off and do other things while this process is happening. We wouldn't want them issuing colliding listing edits while that process is happening.

**Comment by hoffmabc** [comment]
We can always beef this up, but for now, there are less than a handful of stores that have listing counts that would take more than a few seconds. Probably a better UX but way more complexity and testing requirement.

**Comment by hoffmabc** [comment]
> Adding a single Coupon to multiple listings in a bulk update in Settings > Store would also be a nice feature.

I submitted another PR on the go server side for bulk coupon editing.

**Comment by jjeffryes** [comment]
This was completed.
