### ISSUE TITLE
Payment not being detected and sale stuck in Fullfilled status

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1693]
I'm not sure if it is a desktop client or a server issue. I'm using OB v2.3.0 server v0.13.0 on Win 7 64 bits.

**Brief Description:** 
I'm a vendor and can't complete a sale. It was a moderated sale (without dispute), in which I believe the buyer received the product, clicked to pay me (the BTC payment was released to my wallet), but somehow the buyer confirmation/review was not transmitted in the network. I suppose the buyer clicked on release payment, payment was signed (2 of 3), but he closed OB client before the confirmation/review was transmitted to the network.

**Timeline:**
- I sent the product.
- I didn't receive any confirmation (or review) on sales page.
- Buyer released payment, since I received the BTC amount in my OpenBazaar wallet (it was a moderated payment and no dispute was opened). Buyer was not seen online anymore.
- Time to open a dispute has expired.
- Now I want to have this sale listed as _Complete_ in my sales page. But since the payment was already released and I didn't receive any buyer confirmation/review, I'm getting an error when I click on "Claim payment button": _[INFO] [pool/executeRequest] error executing wallet client request: error broadcasting tx: status not ok: 400 Bad Request_

**Observed Behavior:**
1. OB doesn't detect that payment was received in its internal wallet.
2. Vendor doesn't receive any notification that the order was paid.
3. "Claim payment button" doesn't work.
4. Sale status is stuck as _Fullfilled_ and vendor can't change status of the sale to completed.

**Expected Behavior:**
1. OpenBazaar should detect that payment was received in the order's BTC address, even if a confirmation from buyer was not received. 
2. Vendor should be notified that an order was paid.
3. "Claim payment button" shouldn't appear when order's BTC address has already received the payment.
4. Sale status should change to _Paid (waiting buyer confirmation/review)_. After some time, if no sale confirmation is received from buyer, status should change to Complete.

**Comment by placer14** [comment]
@rhcastilhos Everything appears to be working as intended up until the "Claim Payment" step which is clearly returning an error. If we assume the buyer never released payment or that they closed their client before transmitting the order resolution, you should be able to claim the payment after the dispute period ends. This is the intended failsafe for these scenarios.

Regarding `error broadcasting tx: status not ok: 400 Bad Request`, this is an error between the server/daemon and the wallet API which is specific to the state of your wallet. Would you please open a ticket at https://openbazaar.zendesk.com/hc/en-us/requests/new and include `logs/ob.log` which is found in your OpenBazaar data directory. We'll need to look more closely at the state of your node to determine the problem.

Since this is specific to the daemon, I'm going to move this to the appropriate repo and will cross-link here. Thanks for the report!
