### ISSUE TITLE
Add Czech translation

### ISSUE THREAD

**Issue by foxikk** [OpenBazaar/openbazaar-desktop#1817]
Hi, I have just finished translation to Czech language at: https://www.transifex.com/ob1/openbazaar/openbazaar-v2/

Can somebody please add the new language to the project?
Or is the process automated?

I want to test it online to see the context.
Thanks!

**Comment by jjeffryes** [comment]
Thanks @foxikk.

Normally we update the language files right before a release. 

Since it may be a while until our next release, I've created a pull request at #1818 that incorporates your translation file, you can pull that PR now if you want to check it, or download the updated master version once the pull request is merged.
