### ISSUE TITLE
Shipping Option Title

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#182]
We need to give users a couple easy to select defaults here in addition to the free-form. It's obnoxious to have to think of a name for this and not super clear. 

![image](https://cloud.githubusercontent.com/assets/45482/21075930/ce028854-beec-11e6-989e-3282f427491c.png)

**Comment by hoffmabc** [comment]
Come to think of it this treatment would be good on the Shipping Length as well since there are some pretty normal default options I think...not sure what the best UI is here though.

**Comment by morebrownies** [comment]
The shipping option design was inspired by Wix (see screenshot below). We could try to rework the UI and create space for default options, but I'm thinking this will get rather complicated since we're already tight on space as is. 

<img width="298" alt="screenshot 2016-12-12 11 56 38" src="https://cloud.githubusercontent.com/assets/13066886/21114475/1187cfd2-c062-11e6-83ff-9d4276789f05.png">

The bigger underlying issue with shipping (imo) is we don't offer a way to "attach" shipping options to many listings. This introduces a pretty big maintenance problem... 

As a Vendor, if you have 250 listings, and you want all 250 listings to have the exact same shipping option(s), you would need to open each listing independently, manually enter the shipping option(s) and then move on to the next listing. If you ever needed to change your shipping rates, you would have to manually update all 250 listings... This is a major pain in the ass. Ideally there would be one place to update global shipping options and all 250 listings would receive the update. 

We're going to need to explore the idea of shipping templates, but I'm worried this would really increase the scope of 2.0 and push our release date quite a bit. 

The backend alone seems very complicated and could introduce a lot of edge cases, e.g. what if a store has 10k listings? how long would it take to update all the listings? what if the update fails half way through? what if the user goes offline during the update? It gets very complicated...

**Comment by jjeffryes** [comment]
This was closed due to the wrong number being in the comments for a PR.

**Comment by jjeffryes** [comment]
This issue is covered by #329
