### ISSUE TITLE
Make avatar/header size warning less intimidating

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#189]
Reduce the "in your face-ness" of the warnings when a user uploads an image that is too small.

**Comment by drwasho** [comment]
I can confirm that trying to upload images in the client is kinda annoying as it keeps returning errors that it's too small or large... the user expects the client to figure it out. The image may turn out ugly and stretched, but that will encourage the user to choose a better picture.

In that spirit, the help text (i.e. image should be X by Y size) should be more of a suggestion.

I know this is kinda annoying because it's more work for the client to manipulate the image, but it may prevent a user being put offside IMO.

**Comment by rmisio** [comment]
I agree and would lean towards eliminating that message altogether.

Another message in this category, I think is the "This image is too small to zoom". Is that really necessary... or couldn't we just disable the zooming slider. I would think users could figure it out.

![image](https://cloud.githubusercontent.com/assets/794517/21121631/6505a8a8-c082-11e6-80fd-065c9892196b.png)

**Comment by jjeffryes** [comment]
The zoom slider does get disabled, but it isn't clear to the user why. That's why we added that message, because it was confusing when we didn't have it.

**Comment by hoffmabc** [comment]
If the slider wasn't even visible with that be confusing still?

**Comment by jjeffryes** [comment]
If it's sometimes visible and sometimes not, that would be confusing, I think.

**Comment by rmisio** [comment]
> If it's sometimes visible and sometimes not, that would be confusing, I think.

I guess it's a matter of opinion. It's very common in UI's for some element to be disabled and a user may not always immediately know why. I don't recall really seeing cases where some messaging is put in to explain why. Usually, if the user is curious enough they'll figure it out.

@morebrownies what do you think?
