### ISSUE TITLE
Create listing: Save buttons

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-desktop#198]
<img width="914" alt="screen shot 2016-12-13 at 9 49 00 am" src="https://cloud.githubusercontent.com/assets/3887694/21121667/6b9ecc0c-c119-11e6-99b1-aac0e9b7854f.png">

> Yo dawg... I heard you like 'Save' buttons, so I put a save button in your save button, so you can save while you save.

Only one save button is necessary, I suggest the bottom-right makes the most sense.

**Comment by rmisio** [comment]
The reason for that is because if you Edit the listing from the Listing Detail page, the design called for a top bar with 2 buttons:

![image](https://cloud.githubusercontent.com/assets/794517/21199143/1252c534-c1f7-11e6-817b-25b292e1b930.png)

For consistency, when opening the Edit modal from other areas, I left the top bar in and just omit the unneeded button. I could though omit the bar altogether. @morebrownies Is that what you would like?

**Comment by morebrownies** [comment]
>  I could though omit the bar altogether. @morebrownies Is that what you would like?

We need to switch the design of the modal all together @rmisio, so I wouldn't worry about removing the top bar right now.  If we removed it, we'd also lose the **Return to Listing** button, which I find very useful. 

> Only one save button is necessary, I suggest the bottom-right makes the most sense.

@drwasho once we switch to the new modal design, the save button will no longer be fixed at the bottom of the viewport. Instead, it will require the user to scroll down to the very bottom of the overlay and hit **Save**.  [See the prototype](https://invis.io/M79QNWLZ3#/211277807_Openbazaar-2-0-Edit-Listing).

Keep in mind that prototype doesn't have many shipping options filled in so the vertical scroll isn't too bad. For a listing with 5 shipping options filled in, having to always scroll to the very bottom of the screen in order to save could be annoying, especially in the case of making a quick change to the Title or Description field.

I don't see any harm in having 2 buttons.

**Comment by rmisio** [comment]
@morebrownies Is there a design anywhere for the top bar in the new modal style? I remember there was a prototype for that, but I don't have that link anymore.

**Comment by morebrownies** [comment]
@rmisio I probably need to rethink this a bit to account for #194. I'll post something a bit later today.

**Comment by jjeffryes** [comment]
@drwasho @morebrownies is this still considered an issue? We still have two save buttons, at the top and bottom, but they seem useful and look fine to me, considering the height of the form.

**Comment by morebrownies** [comment]
I find myself using both buttons pretty often. I would like to keep them as well.

**Comment by jjeffryes** [comment]
I think we're in agreement, I'll close this issue.
