### ISSUE TITLE
Add Loading State to Follow Button

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#209]
In the user page and user card views, when the follow button is clicked and it is waiting for the follow call to work, it's not clear anything is happening.

Add a loading/in progress state to the button when it is clicked, which is cleared when the call completes, similar to what was used in v1.

Ideally this is done in a way that can easily be applied to any button.

**Comment by rmisio** [comment]
There's already a 'processing' class for this. It's styling is a bit of a placeholder, but we could tweak that once we settle on a spinner.

**Comment by rmisio** [comment]
#355 fixes this in the User Card view.

It still needs to be fixed on the user card on the Home tab in the user page, since that isn't rendering a User Card view, but is just using the template. The more robust fix would be for that to use the actual User Card view, so we don't always need to double-do functionality. The User Card view needs to be adjusted to not necessarily always fetch a Profile model, since in some cases (like this one) you would already have one. At the least that fetch should be opt-out.

**Comment by rmisio** [comment]
FWIW, with the new batch / async profile API, we probably want to make the user card view so that it could place nice with that.

I think the user card should be able to accept a profile model at creation (since the parent may already have one) or have one provided at a later time (e.g. with lists of users, the parent would probably get the profile via the batch API).

If there are use-cases where the user card should create and fetch the profile on it's own, I echo my sentiments above that that functionality should be optional.

**Comment by jjeffryes** [comment]
I agree that the userCard view should be updated to accept a profile, and only fetch it on it's own if a guid is provided with no profile.

**Comment by rmisio** [comment]
this was fixed.
