### ISSUE TITLE
Socket connection failure

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#232]
I got the OB 2.0 client to work, but can't anymore. See screenshot for error. I have deleted `~/Library/Application Support/OpenBazaar2.0`, but that hasn't helped things. Any ideas?

![screen shot 2016-12-20 at 16 27 57](https://cloud.githubusercontent.com/assets/731743/21358688/60296ad6-c6d1-11e6-9f8c-634061a620e1.png)

**Comment by hoffmabc** [comment]
Your server isn't running.

**Comment by JustinDrake** [comment]
My server is running I believe

<img width="1473" alt="screen shot 2016-12-20 at 16 30 38" src="https://cloud.githubusercontent.com/assets/731743/21358777/b391308c-c6d1-11e6-92b7-3d65e4772870.png">

**Comment by hoffmabc** [comment]
1) Did you modify any configuration settings?
2) Did you hit the retry button a couple of times? Sometimes it doesn't retry on it's own?

**Comment by JustinDrake** [comment]
1. No
2. Just tried; doesn't work

**Comment by hoffmabc** [comment]
Ok I will have to pass off to @rmisio or @cpacia then in this case. I haven't seen an issue with this. Are you on latest master for each piece?

**Comment by JustinDrake** [comment]
Yes, running master on both `openbazaar-go` and `openbazaar-desktop`.

**Comment by hoffmabc** [comment]
I just tried on my box and it seems fine. Can you see this url in your browser?

http://localhost:8080/ob/config

**Comment by rmisio** [comment]
Not sure - haven't really had an issue with this unless it's that your server isn't running. I assume you've tried bouncing your server?

The only other thing I could think of is authentication failure. The connection piece is a work in progress and, as of now, even in the case of an auth failure, it would only show this generic error. But... for auth to fail, you must have had to turn it on in the server config... and since you said you haven't changed that, then I'm guessing this is not the issue.

BTW, what does your JS console output look like?

**Comment by JustinDrake** [comment]
Ok, I was being stupid. I was running a server on port `8080`, and that conflicted.

**Comment by rmisio** [comment]
Yeah, we have a server issue to change the default OB port to something less common as 8080. Until that happens, I doubt you'll be the last person to run into this scenario.

**Comment by JustinDrake** [comment]
Cool. I'll reopen then.

**Comment by hoffmabc** [comment]
Let's keep it closed @JustinDrake and leave the server issue open. There's no action here and it's still searchable if someone has the same issue.
