### ISSUE TITLE
Chat emoji

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#251]
Is the intention for the chat box to provide support for Slack-like emojis, e.g. `:simple_smile:` will display a smiley face?

**Comment by morebrownies** [comment]
+1 would really like to see this integrated. 

This library looks pretty good: https://jsfiddle.net/1v03Lqnu/

Github page
https://github.com/mervick/emojionearea

**Comment by rmisio** [comment]
We are planning at some point to integrate emoji support, but I'm not sure we're going to support  slack like notation (e.g. :simple_smile).

The library @morebrownies suggested does have that, but I'm not sure that's the lib we're going to use.

I had my eyes on https://github.com/twitter/twemoji, by Twitter. It seems quite mature and popular, judging by Github stars. It doesn't support that type of short-notation (https://github.com/twitter/twemoji/issues/108) mainly because it claims that there's no standard for that.

**Comment by JustinDrake** [comment]
👍  twemoji looks great. The short-notation can easily be overlaid on top of twemoji if required.

**Comment by rmisio** [comment]
Ok... emoji support is in peer review - #380.

Turns out I did end up implementing short name support. It was actually the quickest path to implement this feature since trying to manage emoji images in the message text input area was full of all types of complications.

Anyhow, since AFIK, there is not any type of standard for the short names, I created them off of the name column here: http://unicode.org/emoji/charts/full-emoji-list.html. For example, 😁 becomes `:grinning_face_with_smiling_eyes:`.

As you can see, it makes some of the names a bit overly verbose, but if anyone's interested, once the PR is merged, they can offer shortened versions here (although they must be unique):
https://github.com/OpenBazaar/openbazaar-desktop/blob/emojis/js/data/emojis.js

===============

FWIW, the client will never save a short name to the database. We will always save out the standard unicode character. The short name is just used as a placeholder in our client (e.g. when you select an emoji from the menu, it will put the short name in the text field). So... different clients can implement short names however they want and as long as they ultimately save the message with the standard unicode character, it will play nice with other clients.

**Comment by supertiger1234** [comment]
> +1 would really like to see this integrated.
> 
> This library looks pretty good: https://jsfiddle.net/1v03Lqnu/
> 
> Github page
> https://github.com/mervick/emojionearea

Has a lot of emojis missing.
