### ISSUE TITLE
Should modals close when the background is clicked?

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#257]
Clicking anywhere outside of the white areas closes the modal currently
![screenshot 2017-01-04 14 23 04](https://cloud.githubusercontent.com/assets/13066886/21661760/a8c5d116-d28a-11e6-8cd2-b7b29cc1087e.png)

It's a standard pattern across the web to be able to click the background to close a modal. However, in OpenBazaar, I find myself accidentally closing the modal pretty often when I'm in Settings, Create listing and on listing details. 

Our modals are pretty loaded and feel more like a standard page, which I think will catch a lot of people off guard and lead to a lot of accidental closing of modals. 

Here are 3 options we can consider:
1) Disable the background click event from closing the modal (Clicking the close icon, back arrow and esc will continue to close the modal)
2) Display a warning when the background is clicked, **Are you sure you want to close the modal?**.  #104 suggests we only do this when there are pending changes to the forms. Doing it all the time could be annoying, especially if accidental clicks happen often. 
3) Keep as is. 

I tend to think we should do a combo of 1 and 2. Remove the background click event and warn users when pending changes may be blown away. 

Thoughts?

**Comment by jjeffryes** [comment]
I've been caught by that too. 

2 by itself would probably be fine, since it would protect you from accidental closing, which is the main problem.

**Comment by rmisio** [comment]
If it's a UX issue, then I would opt for #1 and we should just drive users to close the modal via the X or an esc press, which are much more explicit.

I would think adding a blanket "are you sure you want to close" alert when clicking outside the modal would be really annoying.

As far as only showing that warning if there are unsaved changes... I think that would be nice, but I would defer this for now, since there are complexities with making that work right. For example, if one field on one tab in settings has changed and the user may be on another tab when they close the modal... if we just generically say "There are unsaved changes...", the user may have no clue which changes are unsaved. We could keep track of the changes and take them to the first field that's been changed, but there would be some work there to be able to determine exactly which fields have changed. It's further complicating by the fact that a save may be in progress (in which case, I'm assuming we'd be optimistic and wouldn't warn them that the pending fields changed, because it is a very high likely-hood the save will go through).

**Comment by morebrownies** [comment]
> I would think adding a blanket "are you sure you want to close" alert when clicking outside the modal would be really annoying.

+1

> As far as only showing that warning if there are unsaved changes... I think that would be nice, but I would defer that for now, since there are complexities with making that work right.

+1 We can circle back to #104 when we have time.

> Back click to close a modal. I wouldn't recommend doing that.

Nothing to change here, this already works as expected. When I open a listing, hit back, the listing goes away and I see the Store grid view. 

> As much as is possible we should really drive users to close the modal via the X or the esc press.

Yeah, this is what I was leaning towards as well. Let's remove the background click event and we should be good.
