### ISSUE TITLE
Emphasize release of funds

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#283]
Talking to OB 1.0 moderators, most of the dispute cases arose because buyers didn't release funds. I don't believe the initial release of OB 2.0 will have automatic release of funds in case of buyer inactivity. I have also found that many buyers are not aware they need to release funds.

As such, I think it is important to clearly explain and emphasise the process of releasing funds to mitigate vendor frustration. The only design mockup related to order completion I can find is [this one](https://projects.invisionapp.com/share/TB8GIJS76#/screens/185402065_Openbazaar-2-0-Order-Modal-Direct-Feedback) and the notion of releasing funds to the vendor is not explicit.

cc @morebrownies

**Comment by morebrownies** [comment]
> Talking to OB 1.0 moderators, most of the dispute cases arose because buyers didn't release funds. I don't believe the initial release of OB 2.0 will have automatic release of funds in case of buyer inactivity.

Yeah this is a pretty big problem in my opinion. Users should only pay fees when actual disputes arise, and not when buyers fall asleep. The dispute resolution system isn't working correctly if the majority of cases are due to buyers not hitting a button. 

I suggested a time release on the funds a while back to solve this issue and I think it's something we're still considering. It would also make the underlying contract more clear too if it's known when funds will automatically release. 

If we can't get to that in the short term, we may want to consider sending timed notifications to the buyer 15 days|30 days|45 days after the purchase to release funds. It would help a bit.

**Comment by morebrownies** [comment]
We've decided to work in an automatic time release on the funds.
