### ISSUE TITLE
Don't query resolver.

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#333]
The server takes care of querying the resolver so the client should not do it. See: https://github.com/OpenBazaar/openbazaar-desktop/blob/4bef1d56b01cdb55d9d73caa314a861dd170d0d1/js/utils/index.js

Any API which accepts a guid will also accept an @handle. The server manages caching results. Also the resolver URL is configurable on the server side via the config file. If you hard code it in the client, then it's not configurable.

**Comment by rmisio** [comment]
Need to think about this. I'm not sure it's best to let the server exclusively handle this and then have all endpoints coupled with the resolver call. As it is now, the client has the ability to quickly determine if something is a valid handle and show the appropriate "user not found" page if it's not.

If it needs to be configurable, we could have the server provide the url in the config api.

I feel like there's other repercussions if we hand this control over to the server... but I need to chew on it.

**Comment by cpacia** [comment]
I don't see any benefits only more complexity and more chance for something to go wrong if they both do it.

**Comment by cpacia** [comment]
>  As it is now, the client has the ability to quickly determine if something is a valid handle and show the appropriate "user not found" page if it's not.

You get the exact same response by querying the server endpoint.

**Comment by rmisio** [comment]
The resolver is just a way to provide a handle and get a guid. I think coupling that to individual APIs is an unnecessary complexity.

In our data layer, our Models work off of guids and they have embedded urls based off of those guids. It would be a non-trivial refactor (and ongoing maintenance) to have to provide those models with handles. Besides, IMO, there should be a clear separation of concerns here between the retrieval of the guid and the retrieval of the data.

> I don't see any benefits only more complexity and more chance for something to go wrong if they both do it.

If it's important to you for only the server to handle the resolver part and you want to expose a server API whose sole purpose is to take a handle and return a GUID... that would probably be ok.

But, I think it would be a mistake (and a good amount of work) to have the client's model layer use APIs in a way in which the GUID retrieval and data retrieval are coupled.

**Comment by rmisio** [comment]
Going to close this for now.

> Also the resolver URL is configurable on the server side via the config file. If you hard code it in the client, then it's not configurable.

I agree we would want the url to be configurable. For that, I think the server could either a.) expose a proxied resolver endpoint b.) include the resolver url in the config API.

If either of those happen, we could update the client to follow suit.

**Comment by cpacia** [comment]
If this is going to be a non-trival refactor it should have been discussed before it was implemented. Version 1.0 did not work this way and there was no reason to assume version 2.0

**Comment by jjeffryes** [comment]
I'm pretty sure v1 did work this way, on the client side. Any time there was a handle, it was resolved into a guid before making queries with it. 

We can look at places were calls could be reduced by sending a handle, there are probably some where that would work. But for others that depend on the guid as an ID to build the model first, before the data is fetched, we'll need an API to the resolver.

**Comment by rmisio** [comment]
> I'm pretty sure v1 did work this way, on the client side. Any time there was a handle, it was resolved into a guid before making queries with it.

That's correct. @cpacia What you're presenting to us here is a surprise and deviation from that and, I agree, it certainly beared a discussion much earlier where we could have made it clear to you how coupling GUID retrieval to individual data APIs was less than ideal and perhaps a common ground could have been found earlier.

> It's not trivial for the server to have to share configuration data like with the client for one. 

I think that's something we're going to need to solve one way or another as it's a very common situation for the client to need certain configuration from the server.

Along those lines, why isn't the resolver url in the Settings API, like it was in v1? Having it be in the server config file is problematic for local servers. As of now, the client doesn't manage that config file, so bundled users would be unable to change the resolver url.

Having the client manage the config file would be a good amount of work. It would:

- add more complexity to an already quite complex start-up process
- any time any config in that file is changed, the server would need to be bounced and the user would need to go through the start-up process again
- The settings UI would be further complicated - it's already saving to multiple HTTP api's, localStorage and I certainly wouldn't want to add the file system to that.
- There would not be a consistent UI to change the resolver, since non-bundled users would have to change the config file on their own, so for them we'd have to hide any UI in the client that would save to the config file.

With all those complications added, what is the reasoning for not following suit with v1 and having the resolver as a property of the Settings API?

**Comment by rmisio** [comment]
Ok, after speaking with Josh, the understanding is that we wouldn't need a UI to change the resolver url. If a user using the bundled app needs that changed, they'll need to manually update the config file.

If that's the case, my concerns about the "client manage the config file" are a moot point.

**Comment by hoffmabc** [comment]
So what is the resolution here guys?

**Comment by jjeffryes** [comment]
If @cpacia can provide an end point for the handle resolver, we can update the code to use that instead. 

There are places in the client where the only thing we want to do is input a handle and return a guid for it. 

We can check if there are places in the client where currently that's a two-step process that could be one step instead (sending a handle directly to a back end call instead of getting the guid for the handle first).

**Comment by rmisio** [comment]
Yeah, Chris said he'd provide us a proxied end-point. Once that's in place, there's not a whole lot of work to swap it out and use it on the client.

> We can check if there are places in the client where currently that's a two-step process that could be one step instead (sending a handle directly to a back end call instead of getting the guid for the handle first).

I disagree and don't think we should do that for reasons I've gone into in details above. It's, IMHO,  a bad idea to couple things in that way and would require a good amount of manual work on each end-point associated with a guid.

**Comment by rmisio** [comment]
Closing this since we agreed that the server would provide an endpoint which serves as a proxy to the 3rd party resolver. Once that is in place, the client just needs to update an url.
