### ISSUE TITLE
Some chat weirdness

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#497]
Looks like some confusing overlapping stuff.

![image](https://cloud.githubusercontent.com/assets/45482/26498914/b4c9cf6a-41fe-11e7-846d-6e3fb69b5ddd.png)

**Comment by rmisio** [comment]
@hoffmabc Can you please wipe your DB and see if it still happens?

With a recently merged PR, the chat app ends up throwing an exception and I think this bug is a symptom of that. I think some previous data is not compatible with the new code.

If that doesn't work, can you please post any errors you see in the console when this is happening?

**Comment by hoffmabc** [comment]
I’m not sure I can replicate it again since it’s unread messages and I don’t have any more of them, but I will try.

**Comment by rmisio** [comment]
I think this was fixed.
