### ISSUE TITLE
Spec for `ob://` links

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#586]
What are the valid `ob://`? It seems we have `/store/...` for listings. Are we still going to have `/about`, `/followers`? IPFS has it's own path system and I'm concerned there will be collisions. Already `QmZXGKrRRe5RTDhvzhZfSTe8vYBDGV7HBoNz5FS3U9FnUa/store` is ambiguous, because in the context of IPFS this means the `store` object under `QmZXGKrRRe5RTDhvzhZfSTe8vYBDGV7HBoNz5FS3U9FnUa`. cc @cpacia

**Comment by hoffmabc** [comment]
Will put together a spec guide on this with @jjeffryes and @cpacia. Personally I'm not worried about collisions because we aren't referencing IPFS objects directly like that. This is a UX convenience for the desktop app not really encouraging people to think of these as IPFS URLs.

**Comment by rmisio** [comment]
Also, the desktop client works off of `ob://` if they are ever externally shared. Internally, we route without the `ob://` preface, but our router would never have any need to route directly to an ipfs link. If it did, we'd create the appropriate route and the IPFS data would be fetched via an XHR request.

**Comment by jjeffryes** [comment]
Here's a list of the valid addresses in the reference client:

- **@[handle]** - navigate to a user page based on a handle. Resolves to /store if the user has vendor set to true in their profile, otherwise resolves to /home.
- **peerID** - navigate to a user page based on the peerID. Resolves to /store if the user has vendor set to true in their profile, otherwise resolves to /home.	  
    - **@[handle] or peerID** can be followed by a / and 'home', 'store', 'following', or 'followers'.	  
    - **'/store'** can be followed by the slug for a listing, which will show the listing.	  
-  **transactions** - will resolve to transactions/sales. 
    - transactions can be followed by a / and 'purchases', 'sales', or 'cases'.	  
- **search?[query]** - will load the search screen and execute the query. The query can have the following parameters:	  
    - **providerQ** = encoded url for the provider query. ex: providerQ=https%3A%2F%2Fsearch.ob1.io%2Fsearch%2Flistings%3Fq%3Dbananas%26p%3D0%26ps%3D12 
    - **q** the term to search for
    - **p** the page to start on. If p = 3, page 3 of X will be shown.
    - **ps** the page size. 
    - **sortBy** the value to sort by.
    - Other parameters will be treated as filters.

**Comment by JustinDrake** [comment]
Thanks @jjeffryes.

1) Does `transactions/` take a query? The reference client currently creates the following URI:

> ob://transactions/purchases?sortBy=UNREAD&states=0-1-2-3-4-5-6-7-8-9-10-11-12

2) Can we link to ratings?
3) Can we link to a specific purchase?

**Comment by rmisio** [comment]
> Does transactions/ take a query? The reference client currently creates the following URI:

Yes, the url params map to the different ways to filter the transactions list.

> ob://transactions/purchases?search=abcde&sortBy=UNREAD&states=0-1-2-3-4-5-6-7-8-9-10-11-12

> Can we link to ratings?

You mean the "Reviews" section within the listing overlay? No, not that I'm aware of.

> Can we link to a specific purchase?

Yes, add the orderId as query param:

> ob://transactions/purchases?sortBy=UNREAD&states=0-1-2-3-4-5-6-7-8-9-10-11-12&orderId=QmVvcLYWk2z4itE9t8Jzbava8rs9iPw8HGKabYKay5evXv

FWIW, transactions and orders are something specific to a particular node, so I'm not sure how much it would make sense to share these (i.e. a link with an orderId could be shared between vendor and buyer, but for anyone else it will result in a `Order not found` state). The main reason the state is tracked in the url is a.) to be able to internally link to an order or a transactions list filtered in some specific way b.) If the user refreshes the page, their state is maintained.

**Comment by JustinDrake** [comment]
I'm not sure what `states=0-1-2-3-4-5-6-7-8-9-10-11-12` means.

**Comment by rmisio** [comment]
Those correspond to order states:
https://github.com/OpenBazaar/openbazaar-go/blob/0d0c471a464a55dfd8e57619e06a55b8638fe578/pb/protos/orders.proto

The states map to the different filters in the UI (although it's not always a 1 to 1 mapping):
![image](https://user-images.githubusercontent.com/794517/28641228-5a0bffd2-7203-11e7-8311-8d2259d89853.png)

This list is dash separated because that's more url-friendly than commas.

**Comment by jjeffryes** [comment]
URL specifications can be found here https://github.com/OpenBazaar/openbazaar-desktop/wiki/OpenBazaar-2.0-URLs

**Comment by JustinDrake** [comment]
@jjeffryes Cool. Will the spec be updated the remove handles, and instead use `.ob` as discussed on Thursday?

**Comment by jjeffryes** [comment]
@JustinDrake when we finalize that, or any other change, we'll update the wiki.
