### ISSUE TITLE
Font size discrepancy

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#626]
Why is cancel smaller?

![image](https://user-images.githubusercontent.com/45482/29032412-4f24571c-7b5f-11e7-845e-c5ccb7fc9c0e.png)

**Comment by rmisio** [comment]
I believe that's how the designs had it. @morebrownies Should this be adjusted?

**Comment by hoffmabc** [comment]
Looks off in practice...not sure if intentioned

**Comment by morebrownies** [comment]
I used a smaller font-size on the link to help with potential spacing issues. 

Are there any scenarios when a link and button display like in the design below @rmisio?  

If not, we can bump the font-size. Otherwise, we may be tight on space, especially with some of the translated languages. 

![screenshot 2017-08-07 09 22 24](https://user-images.githubusercontent.com/13066886/29035879-0863f9fc-7b52-11e7-9136-882a0b25914e.png)

**Comment by rmisio** [comment]
> Are there any scenarios when a link and button display like in the design below @rmisio?

Yes, I think the screenshot you showed is at least one example.

> If not, we can bump the font-size. Otherwise, we may be tight on space, especially with some of the translated languages.

Yeah, I would agree. I think as it is now, we have no idea how long translations are, so there is a chance that some translations will cause that button to break to a new line... but if we keep the font size small, we minimize that risk at least a little.

**Comment by rmisio** [comment]
closing as "working as designed".
