### ISSUE TITLE
Two nefarious IP addresses don't close TCP connections

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#701]
The two IP addresses `138.68.225.132` and `138.197.221.100` repeatedly establish TCP connections using different peer IDs to other online peers. The problem is that these connections are not teared down; they just accumulate. Maybe it's a crawler of sorts going a bit wild?

The Vintage Fashion 2.0 store (peer ID QmYsPDkREkhWxvmFK33pNekzjwkPk1SecTnfUkZkdHwqKk) is hosted on `138.68.225.132` so I'm assuming these two IP addresses (both on Digital Ocean) are controlled by OB1.

Are these OB1 addresses? What is going on here?

**Comment by JustinDrake** [comment]
The IP address `165.227.8.166` is also doing something weird.

**Comment by hoffmabc** [comment]
Vintage Fashion is @drwasho. Not sure about the other but we are having some issues with our hosting infrastructure so it could be a problematic node.

**Comment by jjeffryes** [comment]
Is this a desktop client issue?

**Comment by JustinDrake** [comment]
@jjeffryes We're lacking an "openbazaar-misc" issue tracker, for misc issues. See also https://github.com/OpenBazaar/openbazaar-desktop/issues/685

**Comment by hoffmabc** [comment]
@JustinDrake let's file this under the openbazaar-go repo since it seems to be more related to the backend than the front end. Unless we can/should do something about it on the front-end that's where I think issues like this can go. I do agree it's kind of odd having two different repos with no general OpenBazaar questions/bugs but we'll have to triage them the best we can for now.

**Comment by rmisio** [comment]
Closing as this is not the correct repo for this bug.
