### ISSUE TITLE
Add a "testing" flag for listings

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#737]
As we saw with OpenBazaar 1.0 many stores will start off by creating test listings. Just like we have a NSFW flag, having a testing flag would be useful so they can easily discriminated.

**Comment by hoffmabc** [comment]
I think mixing test listings in with the production network is a bad idea. Why? Because we have the testnet network. Maybe we can figure out a way to either encourage them to use that if they type the word "test" or "testing" into their listing or just have a persistent message on the Create Listing page to let them know they can do this.

Maybe @morebrownies or @rmisio or @jjeffryes have some ideas for that.

**Comment by JustinDrake** [comment]
For any listing creating during the Alpha and Beta, the default could be to set the testing flag to true. But having test listings doesn't look professional and Duo is looking to filter them out. It's definitely not something you'd expect on a marketplace like eBay, Amazon or Etsy.

**Comment by hoffmabc** [comment]
I agree with you about the professionalism, but we can't prevent them from creating these listings. We have a test network for a reason. Why would we want yet another class of listings for the UI to have to distinguish between?

**Comment by JustinDrake** [comment]
> We have a test network

Do we? My impression was that only the wallet (which is not strictly speaking part of the OpenBazaar network) works with testnet.

**Comment by hoffmabc** [comment]
Not strictly separate networks, but the contracts should only display in one view of the network or the other based on the flag. So setting the test flag on a listing should not allow it to exist in the main network UI if that is clearer. If we allow this to happen then the UI will now have to account for how it shows and handles test listings and real listings simultaneously, not just filter them out based on if you're trying to see test or main networks.

**Comment by JustinDrake** [comment]
Are you saying that the contracts already have a flag? If so, then great!

Would you mind pointing it out to me in [the pb file](https://github.com/OpenBazaar/openbazaar-go/blob/master/pb/protos/contracts.proto)?

**Comment by hoffmabc** [comment]
I'll have to defer to @cpacia for that right now since he's the one who wrote that code, but I believe right now you could at least see that the listing accepts testnet Bitcoin for payment if you wanted to get started on filtering out test listings.

```
"acceptedCurrencies": [
                "TBTC"
            ],
```

I thought I remembered there being more formal discussion of having a way to filter it out, but not sure the status.

**Comment by jjeffryes** [comment]
That's correct. When we do searches with OB1, we filter on the accepted currency. That easily separates the testnet from mainnet listings, which you want to do in any case, since if you're on mainnet you can't buy testnet listings and vice versa.

@JustinDrake we just added a network flag to the search parameters yesterday, which will make this easier. If you get a search query with network=testnet, you should only show listings that accept TBTC, if you get network=mainnet, only BTC.

In the future when we support more currencies the acceptedCurrencies will be used for that too, and we'll send parameters for what currencies the user can spend. Just a heads up if you want to add that to your roadmap.

**Comment by jjeffryes** [comment]
Regarding the larger issue, I don't think it's clear at all to most users that testnet exists, or how they would switch their server to use it. 

We should put some thought into how we present that in a simple way, so users can safely experiment. 

@morebrownies any thoughts there?

**Comment by rmisio** [comment]
> Regarding the larger issue, I don't think it's clear at all to most users that testnet exists, or how they would switch their server to use it.

One thing to keep in mind is that only users of the stand-alone server can potentially start-up a server in testnet mode. Users of the bundled app have no where to set that option. During alpha, it's hard-coded to testnet and during beta it will be hardcoded to mainnet.

**Comment by hoffmabc** [comment]
We had this same discussion for 1.x and decided it was too much of a haul to add in a quick switch in the app, but we should probably consider it for a later enhancement.

**Comment by morebrownies** [comment]
> @morebrownies any thoughts there? 

I would echo @hoffmabc comment above. Ideally we would have a toggle switch for testnet | livenet, but if the scope is large, probably best to punt on it for now.

**Comment by jjeffryes** [comment]
I don't think we have any plans to add a testnet toggle directly in the app.
