### ISSUE TITLE
Allow for flexible moderator pricing (i.e. fixed fee paid to moderator on every transaction)

### ISSUE THREAD

**Issue by michaelfolkson** [OpenBazaar/openbazaar-desktop#78]
We want to not only attract high quality moderators to OpenBazaar but also incentivize them to invest in their offering and take their moderator duties seriously on the platform. One way of being able to generate more revenue would be to allow them to charge upfront fixed fees on **every** transaction, not just the transactions that result in disputes. This would require an alternative 2-of-3 multisig transaction where a fee is sent directly to the moderator in advance of any dispute. Some may want to charge **both** an upfront fee **and** an additional fee in the event of dispute.

**Comment by cpacia** [comment]
I think this would be easy enough to do, but it might be too much to try to get into the 2.0 release. 

There is also an issue where the output to the moderator needs to be above a certain value to avoid being below the dust threshold. This could limit the usefulness of the feature as you can't really take a 10 cent fee per transaction if it's going to cost you 10 cents in fees to spend the 10 cents you earned. 

Also this would likely have to be a stealth transaction, which would increase the fee the buyer has to pay.

**Comment by wds4** [comment]
Re: 10 cent fee - I can envision two moderator business models, one for low cost items, one for high cost items:
 
1) A moderator takes on only high-cost items and relies on fees from disputed claims which pay a significant amount. This model would leave low-cost items unmoderated.

2) A moderator takes on a (very) high volume of low cost transactions, where the majority of income is generated by baseline fees from undisputed claims.

Let's assume: 
- a moderator charges 1%
- it takes on average 10 minutes of a moderator's time to dispute a claim
- a moderator wants to earn minimum $50 an hour. 
That means a moderator needs to make a minimum of $5 per disputed claim, and moderating any item less than $500 will be not worth the time.

Therefore $500 is the threshold between business model #1 and #2. That's pretty high, and leaves a lot of claims unmoderated. Even if you change the assumptions to: charge 5%, goal is to make minimum wage, you get a ~ $25 threshold, which still leaves a lot of items unmoderated.

The point is that Michael is right, we need baseline fees so that business model #2 is viable and low cost items can attract moderators. Since we're talking low cost items, it would require extremely low baseline fees, way under today's typical bitcoin transaction fee.

So perhaps the utility of what michaelfolkson suggests won't really kick in until the lightning network takes off, which will be what, a year-ish? In which case it's no biggie if it's not in the OB 2.0 release. (Or maybe things will progress faster than that once segwit is adopted, idk.)

**Comment by jjeffryes** [comment]
This is an interesting idea, but we're not planning to implement it.
