### ISSUE TITLE
Incorrect following count

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#804]
Seeing a number of stores report a following count of 1 when it's really zero
![image](https://user-images.githubusercontent.com/4504708/30179393-3cb52af0-93da-11e7-85ea-56fa92668019.png)

Data:
```
 "stats": {
        "followerCount": 0,
        "followingCount": 0,
        "listingCount": 0,
        "ratingCount": 0,
        "averageRating": 0
    },
```

**Comment by hoffmabc** [comment]
I think this might be you following it and then the node not having published the updated count. Is taht correct @jjeffryes @rmisio ?

**Comment by cpacia** [comment]
I have no followers or following in my db or root directory. I'm at zero everywhere.

**Comment by hoffmabc** [comment]
hmm ok not sure about that then. maybe a caching issue.

**Comment by cpacia** [comment]
followsme is also returning false

**Comment by rmisio** [comment]
It's probably because other nodes profiles are cached for 10 minutes (the server is sending back the cache header):

`Cache-Control:public, max-age=600, immutable`

It's probably a good idea to keep that header because otherwise if you wait 30 seconds for someones store to load and then you navigate away and press back, you'll need to wait another 30 seconds.

The downside is that the counts will be off. FWIW, if the user actually clicks on that Following tab, the count will fix itself.
