### ISSUE TITLE
Description text alignment not working

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#820]
v.2.0.10

![errorinalignment](https://user-images.githubusercontent.com/10789865/30225521-28fd3d52-94a9-11e7-96f2-93b49f3dd3ed.png)

**Comment by jjeffryes** [comment]
This appears to be a server issue, the style attributes are being removed when the description is saved.

If we can't adjust the server sanitation to preserve attributes, we'll need to remove any formatting option that depends on them. 

https://github.com/OpenBazaar/openbazaar-go/issues/681

**Comment by rmisio** [comment]
I imagine the sanitizer is removing them because they are potentially malicious. I don't know all the nuances, but maybe you could embed a css `background-url` property that makes a call to a malicious endpoint.

I'd think we need to do at least a cursory analysis to determine if allowing them in completely is OK.

Ideally, the sanitizer could be smart enough to allow style attributes with safe values in. I wonder what the client-side lib does?

**Comment by jjeffryes** [comment]
Per Chris, the backend sanitizer considers the style attribute to be unsafe. 

@morebrownies are you ok with removing the formatting options that require style attributes? Mostly that's the alignment. Images and links keep their attributes (src and href).

**Comment by jjeffryes** [comment]
To be clear, I think we have to remove them, since leaving them in won't work.

**Comment by morebrownies** [comment]
> @morebrownies are you ok with removing the formatting options that require style attributes? Mostly that's the alignment. Images and links keep their attributes (src and href).

This will definitely upset some users, but if we don't have a good solution for it now, then it's best to disable.
