### ISSUE TITLE
After saving a listing, display a "view listing" link next to the save button.

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#835]
We've heard from at least a handful of people that finding the listing they just saved isn't super intuitive. 

After the `Save` button is clicked, and the listing saves succesfully, display a `View listing` link next to the save button. We'll want to be sure to do this next to both `Save` buttons.

![screenshot 2017-09-11 09 56 28](https://user-images.githubusercontent.com/13066886/30286752-8063a0c4-96d7-11e7-989a-d40feeced875.png)

**Comment by rmisio** [comment]
If you open a listing in Edit mode, should this link be there from the start?

**Comment by morebrownies** [comment]
I'm a bit worried people may accidentally click `view listing` prior to hitting save. We don't have any type of alert that pops up when attempting to dismiss unsaved changes. If we had that, I'd say show the link all the time. 

Since we don't have it, i'd suggest only displaying the link after a successful save. 

Thoughts?

**Comment by jjeffryes** [comment]
I think that's a good point. 

Either we should make the view listing link "save and view", or it should only appear after a save when there are no unsaved changes.

Save and View would be a lot easier, I think. 

Or we just make the Save button work that way. What are the scenarios where you'd want to save, but not close the edit view and look at the results of the save?

**Comment by rmisio** [comment]
> Or we just make the Save button work that way. What are the scenarios where you'd want to save, but not close the edit view and look at the results of the save?

That's a big pandoras box you're opening there.. because the save is an async call. While in most cases it happens in ms's, it's possible (e.g. remote server), it may take several seconds and the user could start doing something else. Abruptly having the UI switch on them is probably not ideal. Someone might click save and then open settings, for example. Someone might click save and decide they want to change something and start adjusting the form (those changes would be lost if we automatically re-routed them to the listing detail view).

I think the right fix would be to always have the link there (once a listing is created) and get "`We don't have any type of alert that pops up when attempting to dismiss unsaved changes.`" integrated.

Since that unsaved changes alert is a bit of scope, we may just want to do this (`i'd suggest only displaying the link after a successful save`) as a bridge.

**Comment by morebrownies** [comment]
> Or we just make the Save button work that way. What are the scenarios where you'd want to save, but not close the edit view and look at the results of the save?

One scenario is you add a bunch of shipping options or long description and you want to save your progress before proceeding onto the next section to ensure your work is locked in and saved. 

Creating a good listing could take many hours and I don't think it's safe to assume that after every save the user automatically wants to view the listing detail screen. 

For comparison, Wordpress has 3 actions for a page: `Save` `Preview` and `Publish`. We'll probably want to move towards this direction at some point in the future. 

Wordpress also doesn't automatically show the page after you hit save or publish.

**Comment by morebrownies** [comment]
> Since that unsaved changes alert is a bit of scope, we may just want to do this (i'd suggest only displaying the link after a successful save) as a bridge.

I still prefer this approach as well, at least for the short term. We can revisit later.

**Comment by rmisio** [comment]
@morebrownies I actually did the hard part for this bug. I have a PR where I implement a confirm box if you attempt to close the modal with unsaved changes.

I'm about to implement the view link, but I've discovered it's not very translation friendly. If some of the translations in that top row are too long, we'll run out of space.

![image](https://user-images.githubusercontent.com/794517/31153228-b317847a-a854-11e7-9264-fab4d722b6ce.png)

Do you have an alternate place we could show the link? This wouldn't be some much of an issue for the bottom Save button because there's no Heading text there.

**Comment by morebrownies** [comment]
ugh yeah that's not going to fly. How about here?

![screenshot 2017-10-03 16 38 49](https://user-images.githubusercontent.com/13066886/31154054-601ccc76-a859-11e7-886e-7a9b9761560b.png)

**Comment by morebrownies** [comment]
And the bottom button we could still put the link to the left of it
