### ISSUE TITLE
Add ability to easily clone a listing

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#859]
We had it in 1.0 and it's highly requested in 2.0 already. I'll add designs for it when I get a chance and we can work it into our queue.

**Comment by rmisio** [comment]
If my recollection of how it worked in v1 are correct and we want to mimic that, I think it was just a matter of adding a 'clone' button to the listing card and clicking that button would open the cloned listing in the Create Listing modal.

I'm wondering if we should clear out the `title`, otherwise if a user forgets to update it... the clone listing would have a slug very similar to the initial listing (and that slug can't be changed from our UI)? For example, if they cloned `Big Brown Shoe` and changed all the data, but forgot to change the title, the new listing would have a slug of `big-brown-shoe1`. (If I'm overthinking this, please let me know)

**Comment by morebrownies** [comment]
> If my recollection of how it worked in v1 are correct and we want to mimic that, I think it was just a matter of adding a 'clone' button to the listing card and clicking that button would open the cloned listing in the Create Listing modal.

Correct, I was thinking there would be a 3rd button on the listing card for `clone`

![screenshot 2017-09-13 10 44 29](https://user-images.githubusercontent.com/13066886/30392099-9a7912b0-9870-11e7-9291-bab929dca8fc.png)

> I'm wondering if we should clear out the title, otherwise if a user forgets to update it... the clone listing would have a slug very similar to the initial listing (and that slug can't be changed from our UI)? For example, if they cloned Big Brown Shoe and changed all the data, but forgot to change the title, the new listing would have a slug of big-brown-shoe1. (If I'm overthinking this, please let me know)

Since users may only want to slightly change the title, i would suggest keeping the title input populated. Sure the slug could be similar, but that may be desired too.  It would be annoying to have to copy and paste or rewrite a lot of the title over again. I think it should be a true clone feature and the user can modify input values as needed.

**Comment by morebrownies** [comment]
In the future, we'll probably need to make slug customizable. I noticed Wordpress supports this, but we'll save it for later.

![screenshot 2017-09-13 11 02 34](https://user-images.githubusercontent.com/13066886/30392898-16e26be2-9873-11e7-993f-dbcadf017493.png)

**Comment by jjeffryes** [comment]
Cloned listings with slugs that have numbers on the end if the user doesn't change the title sounds ok to me.

**Comment by tyler-smith** [comment]
> In the future, we'll probably need to make slug customizable. I noticed Wordpress supports this, but we'll save it for later

That might be pretty difficult on the backend. If we're going to want this we should discuss it ASAP.

**Comment by tyler-smith** [comment]
Not just the server, but 3rd party services too. For some reason the slug is used as an ID all over the place.

**Comment by rmisio** [comment]
> Not just the server, but 3rd party services too. For some reason the slug is used as an ID all over the place.

Not just those, but the desktop client as well will have a hard time adjusting. The slug + peerId combo is essentially being used as an ID of a listing.... because the listing does not have a legitimate ID (not maleable identifier). The missing ID was brought up as a major concern months ago, but apparently there were some complications (i think IPFS related) to implementing it and the compromise was that the slug would not be allowed to be changed.

**Comment by morebrownies** [comment]
I've confident OpenBazaar users will desire this type of functionality at some point. Either we can provide the functionality or we could suggest cloning the listing and setting the title correct on the cloned listing. 

However, reviews wouldn't carry over so users may be forever stuck with a slug that doesn't match the product title. Something we should definitely consider more. Not a huge issue right now, but could become a problem in the future.

**Comment by tyler-smith** [comment]
I agree.

FWIW I don't see why see we couldn't use an ID system ala Snowflake instead of slugs, but it's something we'd need to discuss with Chris and probably in a hangout or something realtime.

**Comment by tyler-smith** [comment]
I guess if the server is only given a peer ID and slug it either needs to use that a composite ID. It would make it difficult to use slugs at all perhaps. It's something we'll need to think about.
