### ISSUE TITLE
Add Shipping Rules to Shipping Options

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#974]
## User Story
As a user, I want to be able to have lower shipping when buyers buy more than one of the same item.

As a buyer, I want to see the shipping rules, so I know what kind of discounts are available, and I want to know when I have successfully applied a discount.

### Edit Listing
The edit listing screen will need a way to add and edit shipping rules for each shipping option.

- [x] Each shipping option service should have a field for the price for an additional item.
- [x] The price in that field cannot be blank, it is a required field.

### Listing Details
- [x] The price for additional items should be shown next to the price for the first item in the shipping section.

### Purchase
When a user is purchasing a listing the shipping price for additional items should be shown.

- [ ] The price for additional items should be shown in the shipping service next to the price for the first item.
- [x] The price should be calculated and shown correctly in the receipt.
- [ ] Compensation may be needed for servers still running versions of the code that don't have the secondary shipping field.

**Comment by morebrownies** [comment]
I may have lost my mind thinking about shipping rules all day. Need another set of eyes on this.

@cpacia How could we support the user story below? I believe this is what vendors/buyers want right now.

*User story:* The OpenBazaar store sells stickers and the shipping cost per envelop is **$0.49**. We can fit more than 1 sticker in an envelop, so the shipping cost shouldn't increase for certain quantity ranges. Let's assume we can fit 100 stickers in an envelope, and the actual shipping cost stays fixed at **$0.49** for ground, and fixed at **$5.00** for 2-day. 

How would the UI support this?

First the vendor tries the *flat fee approach*:

https://sketch.cloud/s/xrEGW/all/page-1/openbazaar-2-0-edit-listing-shipping-discounts-flat-fee

I believe this would result in `Ground shipping` costing **$0.49** and `2 day shipping` also costing **$0.49** between quantity ranges 2 - 100, right? So buying 1 sticker with `2 day shipping` would cost: **$5.00**, but buying 2 - 100 would cost: **$0.49**.

Next the vendor tries the *discount approach*:

https://sketch.cloud/s/xrEGW/all/page-1/openbazaar-2-0-edit-listing-shipping-discounts-quantity-2rows

I believe this would result in `Ground shipping` costing **$0.49** and `2 day shipping` costing **$4.51** between quantity ranges 2 - 100, right? So buying 1 sticker with `2 day shipping` would cost: **$5.00**, but buying 2 - 100 would cost: **$4.51**.

Ugh not what they wanted. They want qty: 2 - 100 to cost **$0.49** for `ground shipping` and **$5.00** for `2 day shipping`.

Am I missing something super obvious here? Or are we introducing UX issues and not really solving the primary need?

**Comment by rmisio** [comment]
@wolf I think what you're looking for in that scenario is shipping rules per service, not per shipping option.... which obviously is not how the API has it.

I think a workaround though could be that the two services are broken into two separate shipping options.

Not ideal... either that or the architecture would need to be refactored so the rules are per service. @cpacia would have to comment about the feasibility of the former.

A question I would have though is would per service shipping rules really complicate the UX here? Perhaps if and when we eventually switch to breaking up this modal into sub-modals, it may mitigate that.

**Comment by morebrownies** [comment]
I feel we're approaching this incorrectly. Again, I want to emphasize the user stories and use them as a foundation to build off of. I started from scratch with only the user stories in mind, and designed a UI that I thought would solve the user's needs.

**User story 1:** A vendor sells TVs and the cost to ship each additional TV should multiply the price of all shipping services. For example, shipping 1 TV `ground` costs **$100**, shipping 2 TVs `ground` costs **$200**. For `2 day`, the shipping cost for 1 TV is **$150** and 2 TVs is **$300**, etc.

**User story 2:** A vendor sells business cards and doesn't need to increase the shipping price for any size order. All of the shipping service prices should stay fixed, regardless of quantity ordered.

**User story 3:** The OpenBazaar store sells stickers and the shipping cost per envelop is **$0.49**. We can fit more than 1 sticker in an envelop, so the shipping cost shouldn't increase for certain quantity ranges. Let's assume we can fit 100 stickers in an envelope, and the actual shipping cost stays fixed at **$0.49** for ground, and fixed at **$5.00** for 2-day. 

We need a UI/UX flexible enough to support these 3 scenarios, without requiring the vendor to create special rules for each shipping service. I don't want to put extra burden on the vendor in order to try to make the existing schema work.

Instead, I'm proposing a different approach below. It needs more eyes on it and some feedback, but if we agree it generally looks good, then we should determine how the schema would map to it.

![screenshot 2017-10-24 09 34 03](https://user-images.githubusercontent.com/13066886/31955848-7fc65f38-b89e-11e7-8695-42ee5036601b.png)

The screenshot above suggests that the `Shipping Option` sections would not change at all. Instead, I'm suggesting we introduce a `Shipping Rules`section and allow vendors to choose how **all** shipping service prices should calculate on multiple unit orders.

**Comment by rmisio** [comment]
What is the `New` label for next to the shipping rules? Would it be there for a release or two and then go away?

My big concern with this approach is I'm wondering if it would be too limiting to have Shipping Rules not be per Shipping Option / Service.

For example, are you always going to want the same rule applied to express overnight shipping as you would to standard ground. Maybe on the latter you could offer better quantity discounts, whereas the former is more limited.

**Comment by morebrownies** [comment]
> What is the New label for next to the shipping rules? Would it be there for a release or two and then go away?

Yeah was thinking we should temporarily call out new features somehow, otherwise they may be lost.

> My big concern with this approach is I'm wondering if it would be too limiting to have Shipping Rules not be per Shipping Option / Service.

> For example, are you always going to want the same rule applied to express overnight shipping as you would to standard ground. Maybe on the latter you could offer better quantity discounts, whereas the former is more limited.

It really depends on the user stories we're trying to support right now? Are the 3 stories above good enough for 99% of vendors? Or do 50% vendors need what you're suggesting. I'm not sure, but we probably should have figured that out prior to writing requirements for this task.
